name: Build and deploy Node.js app to Azure Web App - AssignmentBenr2423

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Check for package.json
        run: |
          if [ ! -f package.json ]; then
            echo "Error: package.json not found in $(pwd)"
            exit 1
          fi

      - name: npm install
        run: npm install

      - name: Zip artifact for deployment
        run: zip release.zip . -r -x ".git/*" ".github/*" "node_modules/*"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_8E4B9BF4801345CBABE85C7AAB13E7B3 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F90574F4495F4DEFA65D7F75A7C110FB }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_898D0DA69E90485CBA65A2CBFC45676C }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'AssignmentBenr2423'
          slot-name: 'Production'
          package: .
          startup-command: 'cd /home/site/wwwroot && npm install && npm start'
